AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: sam-app

Globals:
  Function:
    Timeout: 30

Resources:
  HelloRustFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: HelloRust
      Handler: bootstrap.is.real.handler
      Runtime: provided
      MemorySize: 128
      Timeout: 3
      CodeUri: ./rust.zip
      Environment:
        Variables:
          RUST_BACKTRACE: 1

Outputs:
  HelloRustFunction:
    Description: "Hello Rust Lambda Function ARN"
    Value: !GetAtt HelloRustFunction.Arn